#ifndef DISPLAY_HPP
#define DISPLAY_HPP

#include <cstdint>

namespace Display {

enum PIX {
    PIX_DATA_TRANSMITTING,  /* 4G数据正在传输. */
    PIX_DATA_SYM,    /* 4G图标. */
    PIX_DATA_LEVEL_0,   /* 4G信号. */
    PIX_DATA_LEVEL_1,
    PIX_DATA_LEVEL_2,
    PIX_DATA_LEVEL_3,
    PIX_MODE_MANUAL,    /* 模式-手动. */
    PIX_MODE_AUTO,      /* 模式-自动. */
    PIX_MODE_TIMING,    /* 模式-定时. */
    PIX_STATUS_RAIN,    /* 状态-雨雪. */
    PIX_ALERT,          /* 告警. */
    PIX_BATTERY_0,      /* 电池电量. */
    PIX_BATTERY_1,
    PIX_BATTERY_2,
    PIX_BATTERY_3,
    PIX_BAR1,           /* 装饰横线1(上方). */
    PIX_BAR2,           /* 装饰横线2(下方). */   
    PIX_OPENING_PERCENTAGE_TEXT,    /* 开度-文字. */
    PIX_MOTOR_STATUS_OPENING,  /* 电机状态-正在开启. */
    PIX_MOTOR_STATUS_CLOSING,  /* 电机状态-正在关闭 */
    PIX_OPENING_PERCENTAGE_S1_A,    /* 开度第1个段码的第1位. */
    PIX_OPENING_PERCENTAGE_S1_B,
    PIX_OPENING_PERCENTAGE_S1_C,
    PIX_OPENING_PERCENTAGE_S1_D,
    PIX_OPENING_PERCENTAGE_S1_E,
    PIX_OPENING_PERCENTAGE_S1_F,
    PIX_OPENING_PERCENTAGE_S1_G,
    PIX_OPENING_PERCENTAGE_S2_A,    /* 开度第2个段码的第1位. */
    PIX_OPENING_PERCENTAGE_S2_B,
    PIX_OPENING_PERCENTAGE_S2_C,
    PIX_OPENING_PERCENTAGE_S2_D,
    PIX_OPENING_PERCENTAGE_S2_E,
    PIX_OPENING_PERCENTAGE_S2_F,
    PIX_OPENING_PERCENTAGE_S2_G,
    PIX_OPENING_PERCENTAGE_S3_A,    /* 开度第3个段码的第1位. */
    PIX_OPENING_PERCENTAGE_S3_B,
    PIX_OPENING_PERCENTAGE_S3_C,
    PIX_OPENING_PERCENTAGE_S3_D,
    PIX_OPENING_PERCENTAGE_S3_E,
    PIX_OPENING_PERCENTAGE_S3_F,
    PIX_OPENING_PERCENTAGE_S3_G,
    PIX_OPENING_PERCENTAGE_SYM_PERCENTAGE,  /* 开度的百分符号. */
    PIX_TEMP_SYM_SUBZERO,   /* 温度-零下符号 */
    PIX_TEMP_S1_A,
    PIX_TEMP_S1_B,
    PIX_TEMP_S1_C,
    PIX_TEMP_S1_D,
    PIX_TEMP_S1_E,
    PIX_TEMP_S1_F,
    PIX_TEMP_S1_G,
    PIX_TEMP_S2_A,
    PIX_TEMP_S2_B,
    PIX_TEMP_S2_C,
    PIX_TEMP_S2_D,
    PIX_TEMP_S2_E,
    PIX_TEMP_S2_F,
    PIX_TEMP_S2_G,
    PIX_TEMP_S3_A,
    PIX_TEMP_S3_B,
    PIX_TEMP_S3_C,
    PIX_TEMP_S3_D,
    PIX_TEMP_S3_E,
    PIX_TEMP_S3_F,
    PIX_TEMP_S3_G,
    PIX_TEMP_DOT,           /* 段码小数点. */
    PIX_TEMP_SYM,    /* 摄氏度符号与温度文本. */
    PIX_HUMI_S1_A,
    PIX_HUMI_S1_B,
    PIX_HUMI_S1_C,
    PIX_HUMI_S1_D,
    PIX_HUMI_S1_E,
    PIX_HUMI_S1_F,
    PIX_HUMI_S1_G,
    PIX_HUMI_S2_A,
    PIX_HUMI_S2_B,
    PIX_HUMI_S2_C,
    PIX_HUMI_S2_D,
    PIX_HUMI_S2_E,
    PIX_HUMI_S2_F,
    PIX_HUMI_S2_G,
    PIX_HUMI_S3_A,
    PIX_HUMI_S3_B,
    PIX_HUMI_S3_C,
    PIX_HUMI_S3_D,
    PIX_HUMI_S3_E,
    PIX_HUMI_S3_F,
    PIX_HUMI_S3_G,
    PIX_HUMI_DOT,
    PIX_HUMI_SYM,
    PIX_SN_SYM,     /* SN标志. */
    PIX_DATE_YEAR_S1_A,
    PIX_DATE_YEAR_S1_B,
    PIX_DATE_YEAR_S1_C,
    PIX_DATE_YEAR_S1_D,
    PIX_DATE_YEAR_S1_E,
    PIX_DATE_YEAR_S1_F,
    PIX_DATE_YEAR_S1_G,
    PIX_DATE_YEAR_S2_A,
    PIX_DATE_YEAR_S2_B,
    PIX_DATE_YEAR_S2_C,
    PIX_DATE_YEAR_S2_D,
    PIX_DATE_YEAR_S2_E,
    PIX_DATE_YEAR_S2_F,
    PIX_DATE_YEAR_S2_G,
    PIX_DATE_YEAR_S3_A,
    PIX_DATE_YEAR_S3_B,
    PIX_DATE_YEAR_S3_C,
    PIX_DATE_YEAR_S3_D,
    PIX_DATE_YEAR_S3_E,
    PIX_DATE_YEAR_S3_F,
    PIX_DATE_YEAR_S3_G,
    PIX_DATE_YEAR_S4_A,
    PIX_DATE_YEAR_S4_B,
    PIX_DATE_YEAR_S4_C,
    PIX_DATE_YEAR_S4_D,
    PIX_DATE_YEAR_S4_E,
    PIX_DATE_YEAR_S4_F,
    PIX_DATE_YEAR_S4_G,
    PIX_DATE_YEAR_S5_A,
    PIX_DATE_YEAR_S5_B,
    PIX_DATE_YEAR_S5_C,
    PIX_DATE_YEAR_S5_D,
    PIX_DATE_YEAR_S5_E,
    PIX_DATE_YEAR_S5_F,
    PIX_DATE_YEAR_S5_G,
    PIX_DATE_YEAR_S6_A,
    PIX_DATE_YEAR_S6_B,
    PIX_DATE_YEAR_S6_C,
    PIX_DATE_YEAR_S6_D,
    PIX_DATE_YEAR_S6_E,
    PIX_DATE_YEAR_S6_F,
    PIX_DATE_YEAR_S6_G,
    PIX_DATE_YEAR_BAR_1,
    PIX_DATE_YEAR_BAR_2,
    PIX_TIME_S1_A,
    PIX_TIME_S1_B,
    PIX_TIME_S1_C,
    PIX_TIME_S1_D,
    PIX_TIME_S1_E,
    PIX_TIME_S1_F,
    PIX_TIME_S1_G,
    PIX_TIME_S2_A,
    PIX_TIME_S2_B,
    PIX_TIME_S2_C,
    PIX_TIME_S2_D,
    PIX_TIME_S2_E,
    PIX_TIME_S2_F,
    PIX_TIME_S2_G,
    PIX_TIME_S3_A,
    PIX_TIME_S3_B,
    PIX_TIME_S3_C,
    PIX_TIME_S3_D,
    PIX_TIME_S3_E,
    PIX_TIME_S3_F,
    PIX_TIME_S3_G,
    PIX_TIME_S4_A,
    PIX_TIME_S4_B,
    PIX_TIME_S4_C,
    PIX_TIME_S4_D,
    PIX_TIME_S4_E,
    PIX_TIME_S4_F,
    PIX_TIME_S4_G,
    PIX_TIME_DOT,
    PIX_WATCHING_SYM,
    PIX_OK_SYM,
    PIX_ERR_SYM,
    PIX_OTA_SYM,
};

enum NUM_SEG {
    NUM_SEG_OPENING_PERCENTAGE_S1,
    NUM_SEG_OPENING_PERCENTAGE_S2,
    NUM_SEG_OPENING_PERCENTAGE_S3,
    NUM_SEG_TEMP_S1,
    NUM_SEG_TEMP_S2,
    NUM_SEG_TEMP_S3,
    NUM_SEG_HUMI_S1,
    NUM_SEG_HUMI_S2,
    NUM_SEG_HUMI_S3,
    NUM_SEG_DATE_YEAR_S1,
    NUM_SEG_DATE_YEAR_S2,
    NUM_SEG_DATE_YEAR_S3,
    NUM_SEG_DATE_YEAR_S4,
    NUM_SEG_DATE_YEAR_S5,
    NUM_SEG_DATE_YEAR_S6,
    NUM_SEG_TIME_S1,
    NUM_SEG_TIME_S2,
    NUM_SEG_TIME_S3,
    NUM_SEG_TIME_S4,
};

bool init();
bool clear();
bool set_pixel(PIX pix, uint8_t value);
bool set_num_seg(NUM_SEG num_seg, char value);

bool flush();

}

#endif
